name: 'Verify'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  verify:
    name: 'Extended verification'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: 'Checkout complete history'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Temurin from .java-version'
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: 'maven'

      - name: 'Verify'
        run: mvn clean package -Pextended
